<a href="https://colab.research.google.com/github/WildanR19/tugas_naive_bayes/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [195]:
# import package yg digunakan
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [196]:
# import dataset
ds = pd.read_csv("seattle-weather.csv")

In [197]:
# view dimensi dataset [row, attributes]
ds.shape

(1461, 6)

In [198]:
# preview dataset
ds.head()

date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [199]:
# view summary dataset
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


In [200]:
ds.describe()

precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [201]:
ds.describe(include='object')

date weather
count         1461    1461
unique        1461       5
top     2012-01-01    rain
freq             1     641

In [202]:
ds['weather'].unique()

array(['drizzle', 'rain', 'sun', 'snow', 'fog'], dtype=object)

In [203]:
#convert data type into datetime
ds['date'] = pd.to_datetime(ds['date'])

In [204]:
# mengubah isi kolom weather menjadi numerik
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds['weather'] = le.fit_transform(ds['weather'])
ds

date  precipitation  temp_max  temp_min  wind  weather
0    2012-01-01            0.0      12.8       5.0   4.7        0
1    2012-01-02           10.9      10.6       2.8   4.5        2
2    2012-01-03            0.8      11.7       7.2   2.3        2
3    2012-01-04           20.3      12.2       5.6   4.7        2
4    2012-01-05            1.3       8.9       2.8   6.1        2
...         ...            ...       ...       ...   ...      ...
1456 2015-12-27            8.6       4.4       1.7   2.9        2
1457 2015-12-28            1.5       5.0       1.7   1.3        2
1458 2015-12-29            0.0       7.2       0.6   2.6        1
1459 2015-12-30            0.0       5.6      -1.0   3.4        4
1460 2015-12-31            0.0       5.6      -2.1   3.5        4

[1461 rows x 6 columns]

In [205]:
# menghapus kolom date
ds = ds.drop('date', axis = 1)

In [206]:
ds

precipitation  temp_max  temp_min  wind  weather
0               0.0      12.8       5.0   4.7        0
1              10.9      10.6       2.8   4.5        2
2               0.8      11.7       7.2   2.3        2
3              20.3      12.2       5.6   4.7        2
4               1.3       8.9       2.8   6.1        2
...             ...       ...       ...   ...      ...
1456            8.6       4.4       1.7   2.9        2
1457            1.5       5.0       1.7   1.3        2
1458            0.0       7.2       0.6   2.6        1
1459            0.0       5.6      -1.0   3.4        4
1460            0.0       5.6      -2.1   3.5        4

[1461 rows x 5 columns]

In [207]:
x = ds.drop('weather', axis = 1)
# x = ds.iloc[:, [0,3]].values
y = ds['weather']

In [208]:
print(x)

      precipitation  temp_max  temp_min  wind
0               0.0      12.8       5.0   4.7
1              10.9      10.6       2.8   4.5
2               0.8      11.7       7.2   2.3
3              20.3      12.2       5.6   4.7
4               1.3       8.9       2.8   6.1
...             ...       ...       ...   ...
1456            8.6       4.4       1.7   2.9
1457            1.5       5.0       1.7   1.3
1458            0.0       7.2       0.6   2.6
1459            0.0       5.6      -1.0   3.4
1460            0.0       5.6      -2.1   3.5

[1461 rows x 4 columns]


In [209]:
print(y)

0       0
1       2
2       2
3       2
4       2
       ..
1456    2
1457    2
1458    1
1459    4
1460    4
Name: weather, Length: 1461, dtype: int64


In [210]:
# split dataset menjadi train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [211]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1095, 4)
(366, 4)
(1095,)
(366,)


In [212]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [213]:
# training the Naive Bayes on training set
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [214]:
# predict test result
y_pred = model.predict(x_test)

In [215]:
# make confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [216]:
print(cm)

[[  0   0  10   1   0]
 [  0   0  31   0   0]
 [  0   0 150   5   0]
 [  0   0   1   5   0]
 [  0   0 158   5   0]]


In [217]:
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy Score : {acc} ')

Accuracy Score : 0.42349726775956287 
